version: '3.7'

x-app: &default-app
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  healthcheck:
    interval: "60s"
    timeout: "3s"
    start_period: "5s"
    retries: 3

services:
  django:
    extends:
      file: docker-compose.common.yml
      service: django-local
    image: wd-django
    build:
      target: dev
      dockerfile: ./compose/local/django/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      cache_from:
        - wd-django
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ['start']
  vite:
    <<: *default-app
    build:
      context: "./services/frontend"
      target: "development"
      dockerfile: ../../compose/local/vite/Dockerfile
      args:
        - "NODE_ENV=development"
    ports:
      - "3000:3000"
    volumes:
      - "./services/frontend:/node/app:delegated"
      - "/node/app/node_modules"






