name: Build

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup .env
        run: |
          touch .env
          echo "VERSION=test" >> .env
          echo "DEV=True" >> .env
          echo "DATABASE_URL=nope" >> .env
          echo "DJANGO_ALLOWED_HOSTS=*" >> .env
          echo "SECRET_KEY=top_secret" >> .env
      - name: Build
        run: docker compose build
      - name: Test Backend
        run: docker compose --file docker-compose.test.yml  up
      - name: NPM lint
        run: docker compose run --rm vite npm run lint


