name: Run Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend
        run: docker compose build
      - name: Run Tests
        run: docker compose run --rm django pytest
